LumiSpy/lumispy

- lumispy/signals/cl.py
Correct spelling should be subtract / subtraction and not substract / substraction (obsolete spelling according to dictionaries). I hope I have caught all instances.
> Correct spelling of subtract(ion)

- lumispy/__init__.py
- lumispy/io.py
- lumispy/io_plugins/README
- lumispy/io_plugins/__init__.py
- lumispy/io_plugins/attolight.py
- lumispy/signals/cl_sem_spectrum.py
Solving #16 .
Created a modified version of `hs.io.load()` as `lum.io.load()`. The `hs.io.load_single_file()` is modified so it first checks for io_plugins files in lumispy, and if it doesn't find any, then it runs the normal hs.io.load_single_file() from hyperspy.
For now it does the job perfectly, supporting any new file type in the lumispy/io_plugins but also supporting all the hyperspy io_plugins too.
In further PRs, another method should be attempted by adding the `io_plugin` of Attolight to the Hyperspy package.
This will require longer time to be approved, so for now this is a working fix and it makes the process of transporting this code to hyperspy easier.
> IO plugin restructure

- lumispy/hyperspy_extension.yaml
- lumispy/signals/cl_sem_spectrum.py
Its absence was causing a failure of the hyperspy load function in my installation: 
Keyerror in assign_signal_subclass
> Added signal_dimension = -1 to CommonLumi

- lumispy.egg-info/.gitignore
- lumispy/__init__.py
- lumispy/hyperspy_extension.yaml
- lumispy/signals/__init__.py
- lumispy/signals/cl_sem_spectrum.py
- lumispy/signals/cl_spectrum.py
- lumispy/signals/cl_stem_spectrum.py
- lumispy/signals/common_luminescence.py
- lumispy/signals/el_spectrum.py
- lumispy/signals/luminescence_spectrum.py
- lumispy/signals/luminescence_transient.py
- lumispy/signals/pl_spectrum.py
- lumispy/tests/test_signal_registration.py
Now the signal should be registered and setting the `signal_type` will assign to the correct class when loading data or changing class (dimension change or from to lazy signal).
To verify:
```python
>>> import hyperspy.api as hs
>>> hs.print_known_signal_types()
+----------------------------+----------------------------------+----------------------------+----------+
|        signal_type         |             aliases              |         class name         | package  |
+----------------------------+----------------------------------+----------------------------+----------+
|           CL_SEM           |  CLSEM, cathodoluminescence SEM  |       CLSEMSpectrum        | lumispy  |
|          CL_STEM           | CLSTEM, cathodoluminescence STEM |       CLSTEMSpectrum       | lumispy  |
| …
```
> Fix signal registration

- lumispy/io_plugins/attolight.py
- lumispy/signals/common_luminescence.py
- lumispy/signals/luminescence_spectrum.py
This is to make it work with the hyperspy io_plugin to be implemented soon, as decribed in #26.
> Saving background in the metadata, not as a CommonLumi object parameter.

- lumispy/__init__.py
- lumispy/signals/luminescence_spectrum.py
- lumispy/tests/test_axis-conversion.py
- lumispy/utils/axes.py
As discussed in #14, I implemented and extended my function to convert the signal axis to energy. Includes wavelength dependent permittivity of air (minor correction for very precise data). Corrects intensities so that integrals are correct. Defaults to nm, but can handle µm if explicitly set.
Includes two helper functions `nm2eV` and `eV2nm` for back and forth calculation.
> Energy conversion of signal axis

- lumispy/signals/luminescence_spectrum.py
- lumispy/tests/test_utils.py
- lumispy/utils/axes.py
Addes `join_spectra` function to `utils/axes`, which allows to join spectra with partially overlapping signal axes.
> S = lum.join_spectra([S1,S2])
> Add function to join several Signal1D objects along signal axes

- .github/workflows/tests.yml
- README.md
Run test suite with the `non-uniform-axis` branch of hyperspy only for the coverage build. Other build use the release version of hyperspy.
> Test against hyperspy release or dev

- .gitignore
- README.rst
- setup.cfg
- setup.py
I have checked if the packaging is fine and after a few tweaks, it should be good to go!
The `setup.cfg` file can contain other configuration information. There are (more recent) alternatives to `setup.cfg` but these things are still fluid and not necessarily established or well documented.
From the root directory:
```
python setup.py sdist bdist_wheel
```
```
twine check dist/*
```
from a folder not containing the lumispy source code
```
conda create -n test_package python=3.8
pip install --find-links dist lumispy[tests]
```
`dist` is the path to the folder containing the packages
```
conda activate test_package
pytest --pyargs lumispy
````
Relevant links:
- https://packaging.python.org/guides/making-a-pypi-friendly-readme
- https://packaging.python.org/tutorials/packaging-projects/#confi …
> Check packaging

- lumispy/hyperspy_extension.yaml
- lumispy/signals/__init__.py
- lumispy/signals/cl_transient.py
- lumispy/signals/pl_transient.py
- lumispy/tests/test_signal_registration.py
Corrected some aliases of the different LumiSpy classes, e.g. `PL` as alias for `PL` makes no sense
(I realized that in https://github.com/hyperspy/hyperspy-extensions-list/pull/6).
Added the remaining Transient classes we defined in #5, `CLTransient` and `PLTransient`, already from the metadata point of view there will be a difference and I imagine that some methods could also be instrument depenent.
> Class hierarchy update

- lumispy/signals/cl_spectrum.py
- lumispy/tests/signals/test_cl_sem_spectrum.py
- lumispy/tests/utils/test_io.py
HyperSpy 1.6.2 breaks `correct_grating_shift`, because of a regression in `shift1D` - see https://github.com/hyperspy/hyperspy/pull/2729.
With the development version of hyperspy, one test which is still failing and this PR fixes it.
> Fix failing test

- .github/workflows/black.yml
- lumispy/__init__.py
- lumispy/release_info.py
- lumispy/signals/__init__.py
- lumispy/signals/cl_spectrum.py
- lumispy/signals/cl_transient.py
- lumispy/signals/common_luminescence.py
- lumispy/signals/el_spectrum.py
- lumispy/signals/luminescence_spectrum.py
- lumispy/signals/luminescence_transient.py
- lumispy/signals/pl_spectrum.py
- lumispy/signals/pl_transient.py
- lumispy/tests/signals/test_cl_sem_spectrum.py
- lumispy/tests/signals/test_cl_spectrum.py
- lumispy/tests/signals/test_common_luminescence.py
- lumispy/tests/signals/test_luminescence_spectrum.py
- lumispy/tests/test_signal_registration.py
- lumispy/tests/utils/test_axis-conversion.py
- lumispy/tests/utils/test_io.py
- lumispy/tests/utils/test_joinspectra.py
- lumispy/utils/axes.py
- lumispy/utils/io.py
- setup.py
> Black formatting

- lumispy/tests/signals/__init__.py
- lumispy/tests/utils/__init__.py
In https://github.com/hyperspy/hyperspy-extensions-list/runs/2815941965?check_suite_focus=true, only one test is run.
Relevant pytest documentation: https://docs.pytest.org/en/6.2.x/goodpractices.html#tests-as-part-of-application-code
```python
pip install https://github.com/LumiSpy/lumispy/archive/refs/heads/master.zip
pytest --pyargs lumispy
```
Only one file of the test suite is included. 
```python
pip install https://github.com/ericpre/lumispy/archive/refs/heads/fix_test_discovery_dev.zip
pytest --pyargs lumispy
```
All the files of the test suite are included.
> Fix installing test suite from source

- lumispy/tests/utils/test_joinspectra.py
- lumispy/utils/axes.py
Due to https://github.com/hyperspy/hyperspy/pull/2765, I realized that the overlap parameter `r` in `join_spectra` could be non integer, so forcing a conversion if it should be of a different type.
> force r to be int

- CHANGELOG.md
- lumispy/release_info.py
- releasing_guide.md
Mainly documentation updates, see [CHANGELOG.md](https://github.com/LumiSpy/lumispy/blob/main/CHANGELOG.md). 
Released directly to avoid confusion with deleted `non_uniform_axis` in HyperSpy.
> Prepare for Release v0.1.3

- README.md
Internal GitHub links do not work for `README.md` on PyPi (https://pypi.org/project/lumispy/), so replace by global links.
> Make links work on PyPi

- lumispy/signals/cl_spectrum.py
- lumispy/signals/cl_transient.py
- lumispy/signals/common_luminescence.py
- lumispy/signals/el_spectrum.py
- lumispy/signals/luminescence_spectrum.py
- lumispy/signals/luminescence_transient.py
- lumispy/signals/pl_spectrum.py
- lumispy/signals/pl_transient.py
- lumispy/utils/axes.py
- lumispy/utils/io.py
> Fix inconsistent docstring formatting

- doc/source/citing.rst
- doc/source/index.rst
- doc/source/license.rst
- lumispy/__init__.py
- lumispy/components/__init__.py
- lumispy/hyperspy_extension.yaml
- lumispy/signals/__init__.py
- lumispy/signals/cl_spectrum.py
- lumispy/signals/cl_transient.py
- lumispy/signals/common_luminescence.py
- lumispy/signals/el_spectrum.py
- lumispy/signals/luminescence_spectrum.py
- lumispy/signals/luminescence_transient.py
- lumispy/signals/pl_spectrum.py
- lumispy/signals/pl_transient.py
- lumispy/tests/__init__.py
- lumispy/tests/signals/__init__.py
- lumispy/tests/signals/test_cl_sem_spectrum.py
- lumispy/tests/signals/test_cl_spectrum.py
- lumispy/tests/signals/test_common_luminescence.py
- lumispy/tests/signals/test_luminescence_spectrum.py
- lumispy/tests/test_signal_registration.py
- lumispy/tests/utils/__init__.py
- lumispy/tests/utils/test_axis-conversion.py
- lumispy/tests/utils/test_io.py
- lumispy/tests/utils/test_joinspectra.py
- lumispy/utils/__init__.py
- lumispy/utils/axes.py
- lumispy/utils/io.py
- setup.py
> fix license statements, add to user guide

- doc/source/index.rst
- doc/source/user_guide/introduction.rst
- doc/source/user_guide/metadata_structure.rst
Introduce LumiSpy specific conventions on metadata structure as brought up in #53.
Decisions I have taken for the moment:
- 'Spectrometer', 'Detector', and 'Spectral_image' are independent nodes on the 'Acquisition_instrument' level. None of them is really hierarchically below any of the others.
- 'Detector' is the general node and contains the 'detector_type'. This way, general parameters such as the 'exposure_time' are not hidden in a detector-specific subnode.
- Besides 'Grating', the 'Spectrometer' contains an additional subnode 'Filters'.
Open questions:
- Should we have separate 'entrance_slit_width' and 'exit_slit_width' parameters? In serial acquisition both can play a role and (though uncommon) may theoretically be set independently. Alternative would be have a general …
> Metadata structure

- CHANGELOG.rst
- doc/source/index.rst
- doc/source/user_guide/installation.rst
- doc/source/user_guide/introduction.rst
- doc/source/user_guide/signal_axis.rst
- lumispy/signals/cl_spectrum.py
- lumispy/signals/luminescence_spectrum.py
- lumispy/tests/utils/test_axis-conversion.py
- lumispy/tests/utils/test_joinspectra.py
- lumispy/utils/axes.py
- setup.py
- set HyperSpy v1.7 as minimum requirement
- remove error messages for non-availability of non-uniform axes
- remove conditions in tests
- adapt mentions in the documentation
Tests run locally, should work once HyperSpy v1.7 is released.  Merge will need to wait for the release, but can be reviewed already for a speedy release of LumiSpy v0.2 after the HyperSpy release.
> HyperSpy v1.7 adaptions

- CHANGELOG.rst
- CONTRIBUTING.rst
- lumispy/signals/common_luminescence.py
- lumispy/tests/signals/test_common_luminescence.py
- update `scale_by_exposure` according to #109
- some tests can only run with Hyperspy v1.7 (they work locally with the development branch)
- added extra comments in contributors guide
Tests run locally, should work once HyperSpy v1.7 is released.  Merge will need to wait for the release, but can be reviewed already for a speedy release of LumiSpy v0.2 after the HyperSpy release.
> Update metadata used in scale_by_exposure

- lumispy/signals/luminescence_spectrum.py
- lumispy/tests/signals/test_common_luminescence.py
- lumispy/tests/signals/test_luminescence_spectrum.py
- lumispy/tests/utils/test_joinspectra.py
Update warning tests to always use `match`.
Fix black formatting (lint failure).
> Update warning tests + black

- lumispy/signals/luminescence_spectrum.py
- lumispy/tests/signals/test_cl_spectrum.py
- lumispy/tests/signals/test_common_luminescence.py
- lumispy/tests/utils/test_axis-conversion.py
- lumispy/tests/utils/test_joinspectra.py
- lumispy/utils/axes.py
- Fix some of the missing coverage mentioned in #133.
- Fix issue with `to_eV` and `to_invcm` changing the variance of the original signal when the variance is a single `int/float` and `inplace=False` (turned up as `inplace=True` was not covered by the test despite it should have been).
- Remove remnants of old HyperSpy axes scheme in `solve_grating_equation` that turned up as a missing coverage for the line checking the axes type version.
> Improve coverage, fix issue with variance conversion

- doc/source/user_guide/signal_axis.rst
- doc/source/user_guide/utilities.rst
- lumispy/signals/luminescence_spectrum.py
- lumispy/utils/axes.py
As pointed out in https://github.com/hyperspy/rosettasciio/pull/25#discussion_r975075990, we mixed refractive index and permittivity of air in the documentation. Is now made consistent. Additional reference added.
> Correct mentionings of refractive index

- .github/workflows/release.yml
- CHANGELOG.rst
xref https://github.com/LumiSpy/lumispy/issues/76
- [n/a] docstring updated (if appropriate),
- [n/a] update user guide (if appropriate),
- [n/a] added tests,
> Remove deprecated `create-release` action and use `softprops/action-gh-release` instead

- .github/workflows/tests.yml
- CHANGELOG.rst
- lumispy/tests/utils/test_axis-conversion.py
- lumispy/utils/axes.py
Fixes #155.
`.isig[]` was failing on signals converted using `to_eV()` or `to_invcm()`.
For tests to run, deprecated `--use-feature=2020-resolver` had to be removed from `PIP_ARGS` in `workflows/tests.yml`
- [n/a] docstring updated (if appropriate),
- [n/a] update user guide (if appropriate),
```
import hyperspy.api as hs
S = hs.signals.Signal1D(np.arange(100),axes=[{'axis': np.arange(100)+300}])
S.set_signal_type("CL")
S.to_eV(inplace=True)
S.isig[3.251:4.052]
```
> Fix slicing of energy/wavenumber signal with isig

- lumispy/signals/luminescence_spectrum.py
- lumispy/tests/utils/test_axis_conversion.py
- lumispy/utils/axes.py
Addresses point 1 in #152.
The axis conversion code was hard to read as routines were repeated for different situations, therefore
- reduced the differences between `inplace=True/False` cases
- and created a generalized utility function to combine code that is universal to the conversions and then call the correct subfunctions
Paves the way for more generalized unit conversion handling (i.e. any conversion between nm, eV and cm^-1).
- [n/a] update user guide (if appropriate),
> Simplify axes conversion code

- CHANGELOG.rst
- doc/source/conf.py
As brought up in #166, math is not rendering any more in the ReadTheDocs.
AS brought up by @hakonanes in https://github.com/hyperspy/hyperspy/pull/3050#issuecomment-1386765990 `sphinx.ext.mathjax` should be working, while `sphinx.ext.imgmath` seems to be broken (in both HyperSpy and LumiSpy).
Therefore replacing the extension.
Fixes #166
> Replace imgmath by mathjax sphinx-extension

- doc/source/index.rst
- doc/source/user_guide/bibliography.rst
- doc/source/user_guide/fitting_luminescence.rst
- doc/source/user_guide/installation.rst
- doc/source/user_guide/introduction.rst
- doc/source/user_guide/metadata_structure.rst
- doc/source/user_guide/signal_axis.rst
- doc/source/user_guide/signal_tools.rst
- doc/source/user_guide/utilities.rst
Split `signal tools` page out of the `utilities page in the user guide. Add some important HyperSpy functions.
Some additional small improvements to the documentation.
Closes #171.
> Add signal tools page to documentation

- doc/source/user_guide/fitting_luminescence.rst
- doc/source/user_guide/introduction.rst
- doc/source/user_guide/metadata_structure.rst
- doc/source/user_guide/signal_tools.rst
- lumispy/signals/cl_spectrum.py
Fixed references in the documentation and added some more links to the fitting section.
- [n/a] added line to CHANGELOG.md,
> Fix links in documentation

- doc/source/user_guide/signal_tools.rst
- lumispy/signals/luminescence_spectrum.py
- lumispy/tests/signals/test_cl_spectrum.py
- lumispy/tests/signals/test_luminescence_spectrum.py
I realized that for a map the new centroid function, similar to e.g. `valuemax` and `indexmax` in HyperSpy returns a `BaseSignal` with 2 navigation dimensions and 0D signal, which theoretically makes sense, but is inconvenient for plotting as it plots including the navigator, which makes little sense for 0D signals, and colormap cannot be changed.
In contrast, `estimate_peak_width` returns the transposed signal, thus `Signal2D` object without navigation dimensions, which is more convenient for plotting - and is okay in the sense that it is just an image of values for the different positions. The `as_signal` command for parameters from a fit also results in `Signal2D`. I therefore think, it is the more sensible output here.
We should consider making that more consistent also in HyperSpy …
> Transpose centroid output

- CHANGELOG.rst
- lumispy/release_info.py
I'd like to push a patch release before the tutorial at the CL-EBIC workshop next week.
> Release_v0.2.2

- lumispy/tests/signals/test_cl_spectrum.py
Fixes the failing test in #185
> fixed test

- .github/workflows/doc.yml
- CHANGELOG.rst
- CONTRIBUTING.rst
- doc/conf.py
- doc/index.rst
- doc/user_guide/fitting_luminescence.rst
- doc/user_guide/installation.rst
- doc/user_guide/introduction.rst
- doc/user_guide/metadata_structure.rst
- doc/user_guide/signal_axis.rst
- doc/user_guide/signal_tools.rst
- doc/user_guide/utilities.rst
- setup.py
- Add intersphinx links after HyperSpy2.0/ExSpy0.1 release (Closes #174).
- Add workflow to test doc build including links and correct links
- Adapt documentation based on HyperSpy2.0 release
> Correct links in docs

- doc/citing.rst
- pyproject.toml
- Fix towncrier in `pyproject.toml` (See also https://github.com/hyperspy/hyperspy/pull/3400#issuecomment-2262444304 )
- Update Zenodo DOI versioning link
> Fix failing documentation builds

- .github/workflows/release.yml
- .github/workflows/tests.yml
- doc/conf.py
- doc/user_guide/streak_images.rst
- lumispy/hyperspy_extension.yaml
- lumispy/signals/luminescence_transientspec.py
- lumispy/tests/signals/test_luminescence_transient_spectrum.py
- upcoming_changes/223.new.rst
When operating over either time or spectral axes of a `LumiTransientSpectrum` signal, e.g. to fit the same function at all times or all wavelengths/energies, it is convenient to have this dimension as a navigation instead of signal dimension. Therefore, `time2nav` and `spec2nav` functions are added.
```python
import lumispy as lum
import numpy as np
ax0 = {"name": "Time", "units": "ps", "size": 10}
ax1 = {"name": "Wavelength", "units": "nm", "size": 10}
s = lum.signals.LumiTransientSpectrum(np.ones(100).reshape(10, 10), axes =[ax0, ax1])
s.time2nav().axes_manager
s.spec2nav().axes_manager
```
> Convert either of the TransientSpec signal axes to navigation axes

- .github/workflows/tests.yml
- pyproject.toml
- upcoming_changes/225.maintenance.rst
A few sentences and/or a bulleted list to describe and motivate the change:
- Add support for python 3.13
- Drop support for python 3.8
- Test for oldest supported hyperspy version and pin to >=v1.7.3
> Add support for python 3.13

- CHANGELOG.rst
- pyproject.toml
- releasing_guide.md
- upcoming_changes/205.enhancements.rst
- upcoming_changes/205.new.rst
- upcoming_changes/211.doc.rst
- upcoming_changes/211.maintenance.rst
- upcoming_changes/223.new.rst
- upcoming_changes/225.maintenance.rst
Release new version 0.3.0 following [releasing guide](https://github.com/LumiSpy/lumispy/blob/main/releasing_guide.md)
> Release 0.3.0
