LumiSpy/lumispy

README.md, lumispy_demos/AttolightSEM_HYP.ipynb
Include an installation guide in the ReadMe starter file.
=> Edit README

README.md, lumispy/signals/cl.py, lumispy_demos/AttolightSEM_HYP.ipynb
This is an update of the early version of LumiSpy.
=> Small corrections, add crop_edges() function

lumispy/utils/io_utils.py
Updated the get_metadata functions, so more parameters are extracted from the MicroscopeStatus.txt file
=> Expand metadata functions

lumispy/signals/cl.py, lumispy/utils/io_utils.py
The following common simple functionalities have been added:
- Background subtraction
- Background storage as metadata (upon loading file from folder for Attolight)
- Cosmic rays removal (spike removal). Very simple, needs further modifications.
=> Added final common functionalities for CLSpectrum class

README.rst, lumispy/signals/cl.py, lumispy/utils/io_utils.py
- Added a User Inerface functionality when loading a file, which let's you select the `HYP_Card` object straight from the browser.
- Added some extra metadata functionalities
- Corrected some minor mistakes
=> Added UI loading functionality

README.md, lumispy/hyperspy_extension.yaml, lumispy/release_info.py, setup.py
Just some small corrections/additions to some of the base files
=> minor corrections

lumispy/io_plugins/attolight.py
Small spelling mistake and wrong file name in metadata.
=> Small fix on load function

.travis.yml, azure-pipelines.yml, conda_environment.yml, conda_environment_dev.yml
Here Travis is only used to install via pypi and Azure to install via anaconda only.
=> Using Azure and Travis properly

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, INSTALLATION.md, README.md, lumispy/signals/common_luminescence.py
- Added template for pull requests
- Added Contributing.md
- Put installation instructions in separate file
=> PR template, contributing

lumispy/signals/luminescence_spectrum.py
As the title says, mainly formatting.
=> Just some typos and formatting

lumispy/signals/luminescence_spectrum.py, lumispy/tests/test_axis-conversion.py, lumispy/utils/axes.py
Added a solver for the grating/spectrometer equation. 
- A `utils.axis` function that converts an axis in pixel/undefined units to wavelength in nanometers
- A `px_to_nm_grating_solver` in the `LumiSpectrum` class that converts the object's signal axis to wavelength in nanometers.
```python
import lumispy as lum
import numpy as np
s = LumiSpectrum(np.ones(20),))
s.px_to_nm_grating_solver(*exp_paramers , inplace=True)
s.axes_manager.signal_axes[0].units
>> 'nm'
```
=> Grating solver

INSTALLATION.md, README.md, setup.py
This follows from #59 and #60.  
After successfully updating the first version of lumispy in pipy, I had to make a few changes:
- Change version to `v.0.1.1` (where we will add all the Github actions...` and fix anything I did wrong (but I still had to do it to get a first release)
- Changed installation instructions
- Added Zenodo badge
=> V0.1 Post Release

.github/workflows/tests.yml, README.md
=> Try codecov instead of coveralls

README.md
=> License badge, citing

README.md
Finalising #65 
Added logo files (`.svg`) in the docs folder.
Added logo in the readme.
=> Add logo files and logo in README

README.md
and use absolute path so that it would work even if files are not included, e.g. on pypi
=> Resize the logo in README.md

.github/workflows/release.yml
fix from https://github.com/LumiSpy/lumispy/issues/81#issuecomment-872542333
=> Add permission at the job level to create release. 

.github/workflows/release.yml, .github/workflows/tests.yml, CHANGELOG.md, azure-pipelines.yml, conda_environment.yml, conda_environment_dev.yml, lumispy/release_info.py
PR to prepare release of ~v.0.1.1~ v0.1.2, see #81
=> Release v0.1.2

README.md
=> correct badges

README.md
Addresses #86 so that the `Readme.md` should be properly rendered on Pypi.
=> Fix image link for Pypi

.github/PULL_REQUEST_TEMPLATE.md, README.md, releasing_guide.md
=> Change the use of 'master' to 'main'

.readthedocs.yaml, doc/source/conf.py, lumispy/tests/utils/test_axis-conversion.py, setup.py
Allows to toggle `>>>` in the examples in the documentation. Adapted from HyperSpy.
=> Add Toggleprompt to sphinx

CONTRIBUTING.rst, doc/source/conf.py, doc/source/index.rst, doc/source/user_guide/introduction.rst, doc/source/user_guide/signal_axis.rst
Wrote introduction page for the documentation.
ToDo:
=> Documentation introduction

.github/workflows/release.yml, .github/workflows/tests.yml, CHANGELOG.rst, setup.py
Added support for python 3.10 in analogy to https://github.com/hyperspy/hyperspy/pull/2914
Drop 3.6
=> Add python 3.10

doc/source/user_guide/fitting_luminescence.rst
Added some notes and links in the fitting section of the user guide.
=> some notes in fitting guide

doc/source/index.rst, doc/source/user_guide/utilities.rst
Add documentation on various useful functions.
=> Add documentation of utility functions

CHANGELOG.rst, lumispy/release_info.py
=> LumiSpy Release v0.2

doc/source/citing.rst
Link to concept DOI in userguide (instead of specific version).
=> change to concept DOI

CHANGELOG.rst, doc/source/index.rst, doc/source/user_guide/utilities.rst, lumispy/signals/common_luminescence.py, lumispy/tests/signals/test_common_luminescence.py
Filled the different proposed sections of `utilities.rst`
=> Write utility documentation

lumispy/signals/cl_spectrum.py, lumispy/signals/common_luminescence.py, lumispy/signals/common_transient.py, lumispy/signals/el_spectrum.py, lumispy/signals/luminescence_spectrum.py, lumispy/signals/luminescence_transient.py, lumispy/signals/luminescence_transientspec.py, lumispy/signals/pl_spectrum.py, lumispy/tests/signals/test_common_luminescence.py, lumispy/utils/axes.py
Fix warnings and recommendations from [lgtm.com](https://lgtm.com/projects/g/LumiSpy/lumispy)
=> lgtm.com fixes

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.rst, README.md, doc/source/index.rst, lumispy/signals/cl_spectrum.py, lumispy/signals/luminescence_spectrum.py, lumispy/utils/__init__.py, lumispy/utils/axes.py
- Follow up on #131 for remaining hits.
- add badges to readme/documentation
- lgtm commenting should now be activated
=> Fix remaining lgtm hits, add badges

doc/source/index.rst
Change in badges of Readme was not properly transferred to documentation index page.
=> Fix badges in doc

doc/source/user_guide/signal_axis.rst
=> fix typo in formula

doc/source/user_guide/installation.rst
Trying to install lumispy for someone else the other day, I encountered some issues that were not clear from the guide. Have added some clarifications.
=> Update installation instructions

.gitignore, lumispy/tests/signals/test_cl_spectrum.py
Tests were broken. Trying to fix them before adding new features
=> fix test error due to hyperspy 1.7 changes

lumispy/signals/luminescence_spectrum.py, lumispy/tests/signals/test_luminescence_spectrum.py
Add tests for `px_to_nm_grating_solver`
=> Improve coverage

lumispy/signals/luminescence_spectrum.py, lumispy/tests/signals/test_luminescence_spectrum.py
=> Fix for numpy 1.24

CHANGELOG.rst, lumispy/release_info.py
I think enough bug-fixes have accumulated for a patch release, 
see https://github.com/LumiSpy/lumispy/milestone/3?closed=1
=> Release v0.2.1

CHANGELOG.rst, README.md, doc/source/index.rst, lumispy/utils/axes.py
=> Replace LGTM badge by CodeQL

doc/source/conf.py, lumispy/signals/cl_spectrum.py, lumispy/tests/utils/test_axis_conversion.py, lumispy/utils/axes.py, setup.py
Fixes warnings and notes from CodeQL scan: https://github.com/LumiSpy/lumispy/runs/9372886548
- avoid loading files without closing
- remove unused import
- remove commented-out code.
=> fix codeql warnings and notes

.gitignore, CONTRIBUTING.rst, doc/source/conf.py, doc/source/user_guide/signal_tools.rst, doc/source/user_guide/utilities.rst, setup.cfg, setup.py
Fixed a link to kikuchipy's contributing guide in the LumiSpy contributing guide by making it "dynamic" with Intersphinx. Also fixed the Sphinx version in `setup.py` so installing in editable mode with `pip install -e .` from root works.
=> Small improvements to docs

.github/PULL_REQUEST_TEMPLATE.md
=> typo PR template

azure-pipelines.yml
Fix Azure Pipelines CI following the deprecation of Mambaforge (now identical as Miniforge).
=> Fix Azure Pipelines CI

doc/conf.py
(user_guide/bibliography: line   16) broken    https://doi.org/10.1063/5.0080486 - 403 Client Error: Forbidden for url: https://pubs.aip.org/rsi/article/93/5/053702/2844887/Image-shift-correction-noise-analysis-and-model
=> Ignore doi error

lumispy/__init__.py, lumispy/components/__init__.py, lumispy/hyperspy_extension.yaml, lumispy/signals/__init__.py, lumispy/signals/cl_spectrum.py, lumispy/signals/common_luminescence.py, lumispy/signals/common_transient.py, lumispy/signals/el_spectrum.py, lumispy/signals/luminescence_spectrum.py, lumispy/signals/luminescence_transient.py, lumispy/signals/luminescence_transientspec.py, lumispy/signals/pl_spectrum.py, lumispy/tests/__init__.py, lumispy/tests/signals/__init__.py, lumispy/tests/signals/test_cl_sem_spectrum.py, lumispy/tests/signals/test_cl_spectrum.py, lumispy/tests/signals/test_common_luminescence.py, lumispy/tests/signals/test_luminescence_spectrum.py, lumispy/tests/signals/test_luminescence_transient_spectrum.py, lumispy/tests/test_signal_registration.py, lumispy/tests/utils/__init__.py, lumispy/tests/utils/test_axis_conversion.py, lumispy/tests/utils/test_io.py, lumispy/tests/utils/test_joinspectra.py, lumispy/utils/__init__.py, lumispy/utils/axes.py, lumispy/utils/io.py
=> Update year in copyright notice
